---
- name: Ensure GitHub user accounts are present.
  user:
    name: "{{ item.username | item.name | default(item) }}"
    shell: "{{ item.shell | default(item) }}"
    groups: "{{ item.groups | default(omit) }}"
    createhome: yes
    home: "/home/{{ item.username | item.name | default(item) }}"
    state: present
    become: true
  with_items: "{{ github_users }}"

- name: Ensure authorized_keys for GitHub user accounts are present.
  authorized_key:
    user: "{{ item.username | item.name | default(item) }}"
    key: "https://github.com/{{ item.name | default(item) }}.keys"
    manage_dir: yes
    exclusive: "{{ github_users_authorized_keys_exclusive }}"
    become: true
  with_items: "{{ github_users }}"

- name: Ensure user accounts in github_users_absent are absent.
  user:
    name: "{{ item.name | default(item) }}"
    state: absent
    become: true
  with_items: "{{ github_users_absent }}"
