---
- name: Ensure GitHub user groups are present.
  become: true
  group:
    name: "{{ item.username | default(item.name) | default(item) }}"
    state: present
  with_items: "{{ github_users }}"

- name: Ensure GitHub user accounts are present.
  become: true
  user:
    user: "{{ item.username | default(item.name) | default(item) }}"
    shell: "{{ item.shell | default('/bin/bash') }}"
    group: "{{ item.username | default(item.name) | default(item) }}"
    groups: "{{ item.groups | default(omit) }}"
    createhome: yes
    home: "/home/{{ item.username | default(item.name) | default(item) }}"
    state: present
  with_items: "{{ github_users }}"

- name: Ensure authorized_keys for GitHub user accounts are present.
  become: true
  authorized_key:
    user: "{{ item.username | default(item.name) | default(item) }}"
    key: "https://github.com/{{ item.name | default(item) }}.keys"
    manage_dir: yes
    exclusive: "{{ github_users_authorized_keys_exclusive }}"
  with_items: "{{ github_users }}"

- name: Ensure user accounts in github_users_absent are absent.
  become: true
  user:
    name: "{{ item.name | default(item) }}"
    state: absent
  with_items: "{{ github_users_absent }}"
